@startuml


'연습문제 1-8
고객  --> "0..*" 신용카드


'연습문제 1-10
class  작업하기{
   - 일시: DateTime
   + 작업 기간: Duration
}

사원 "0..*" - "0..*" 작업
(사원, 작업) .. 작업하기


'연습문제 1-11
class  작업하기2{
   - 일시: DateTime
   + 기간: Duration
}

사원2 -- "*" 작업하기2
작업하기2 "*" -- 작업2
together {
  class 사원2
  class 작업하기2
  class 작업2
}


'연습문제 1-14
회원 <|-- 기업회원
회원 <|-- 개인회원
기업회원 -- 대표


'연습문제 1-16
과목 "1" -- "0..*" 과목


'연습문제 1-17
class 주문정보{
    물품 이름
    물품 구입 개수
    단가
}

고객2 -- "0..*" 주문
주문 -- "1..*" 결제
결제 <|-- 체크카드
결제 <|-- 신용카드2
결제 <|-- 현금
주문 *-- 주문정보


'연습문제 1-18
interface 회전가능한것 {
}
회전가능한것 <|.. 바람개비
회전가능한것 <|.. 선풍기
회전가능한것 <|.. 헬리콥터

@enduml
