@startuml

class Battery {
+ setDisplay(display : BatteryLevelDisplay)
+ setWarning(warning : LowBatteryWarning)
+ consume()
+ getLevel()
}

class BatteryLevelDisplay {
+ update()
}

class LowBatteryWarning {
+ update()
}

Battery <--> BatteryLevelDisplay

LowBatteryWarning <-> Battery

@enduml
