@startuml

class Client {
}

class Context {
- strategy : Strategy
+ setStrategy(strategy : Strategy)
+ do()
}

interface Strategy {
+ execute()
}

class StrategyA {
+ execute()
}

class StrategyB {
+ execute()
}

class StrategyC {
+ execute()
}


Context o-> Strategy
Strategy <|... StrategyA
Strategy <|... StrategyB
Strategy <|... StrategyC
Client -> Context
Client ...> StrategyA
@enduml
